- block:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - php-fpm_update-cache

    - block:
        - name: install php-fpm
          apt:
            name: php7.0-fpm
            state: present
          tags:
            - php_fpm_install-packages
      when: ansible_distribution == 'Ubuntu'

    - block:
        - name: install php-fpm
          apt:
            name: php5-fpm
            state: present
          tags:
            - php_fpm_install-packages
      when: ansible_distribution == 'Debian'
      
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- block:
    - name: install epel repository
      yum:
        name: epel-release
        state: present
      tags: install_packages

    - name: intall php-fpm
      yum:
        name: php-fpm
        state: present
      tags: php_fpm_install-packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
