---
- name: restart php-fpm
  become: true
  service:
    name: php-fpm
    state: restarted

- name: restart php7.0-fpm
  become: true
  service:
    name: php7.0-fpm
    state: restarted

- name: restart php5-fpm
  become: true
  service:
    name: php5-fpm
    state: restarted
